"""Add product models

Revision ID: 76d0cf7551cb
Revises: add_account_linking_constraints
Create Date: 2025-09-16 11:58:58.890237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d0cf7551cb'
down_revision = 'add_account_linking_constraints'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('retail_min_price', sa.Float(), nullable=True),
    sa.Column('retail_min_base_price', sa.Float(), nullable=True),
    sa.Column('available_to_buy', sa.Boolean(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('small_image', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('price_limit', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_foreign_key(None, 'product_category', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'product_category', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'product_image', 'images', ['image_id'], ['id'])
    op.create_foreign_key(None, 'product_image', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'product_video', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'requirements', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'restrictions', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restrictions', type_='foreignkey')
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.drop_constraint(None, 'product_video', type_='foreignkey')
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('images')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
