"""Add orders table

Revision ID: 8e62ef095fa1
Revises: 8724bcc16a6e
Create Date: 2025-09-24 12:34:24.175060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e62ef095fa1'
down_revision = '8724bcc16a6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
