"""add_payment_fields_to_orders

Revision ID: 94e519b51d81
Revises: 8e62ef095fa1
Create Date: 2025-09-25 09:32:46.458412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94e519b51d81'
down_revision = '8e62ef095fa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new payment-related fields to orders table
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('orders', sa.Column('g2a_transaction_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivered_key', sa.String(), nullable=True))
    
    # Create indexes for new fields
    op.create_index(op.f('ix_orders_stripe_payment_intent_id'), 'orders', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove indexes for payment fields
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_stripe_payment_intent_id'), table_name='orders')
    
    # Remove payment-related columns
    op.drop_column('orders', 'delivered_key')
    op.drop_column('orders', 'g2a_transaction_id')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
