"""Add email queue table

Revision ID: add_email_queue_001
Revises: 
Create Date: 2025-09-30 16:01:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_email_queue_001'
down_revision = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('email_type', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_queue_email_type'), 'email_queue', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_queue_id'), 'email_queue', ['id'], unique=False)
    op.create_index(op.f('ix_email_queue_next_retry_at'), 'email_queue', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_email_queue_order_id'), 'email_queue', ['order_id'], unique=False)
    op.create_index(op.f('ix_email_queue_priority'), 'email_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_email_queue_status'), 'email_queue', ['status'], unique=False)
    op.create_index(op.f('ix_email_queue_to_email'), 'email_queue', ['to_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_queue_to_email'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_status'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_priority'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_order_id'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_next_retry_at'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_id'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_email_type'), table_name='email_queue')
    op.drop_table('email_queue')
    # ### end Alembic commands ###
